###
POST https://chatbotstudio.rezayogaswara.dev/api/v1/token/
accept: application/json
Content-Type: application/json

{
  "username": "reza",
  "password": "reza"
}

> {% client.global.set("access_token", response.body.access_token); %}


####

GET https://chatbotstudio.rezayogaswara.dev/api/v1/users/
accept: application/json
Content-Type: application/json

####

GET https://chatbotstudio.rezayogaswara.dev/api/v1/templates/
accept: application/json
Content-Type: application/json

####

#
#POST https://chatbotstudio.rezayogaswara.dev/api/v1/users/
#accept: application/json
#Content-Type: application/json
#
#{
#  "username": "efcd",
#  "name": "efcd",
#  "password": "efcd",
#  "email": "reza.yoga@live.com",
#  "is_active": false
#}

###

GET https://chatbotstudio.rezayogaswara.dev/api/v1/templates/a194cdbd-0894-4828-afb3-d5273602b463/
accept: application/json
Content-Type: application/json
Authorization: Bearer {{access_token}}


###

GET https://chatbotstudio.rezayogaswara.dev/api/v1/template-contents/
accept: application/json
Content-Type: application/json


###

GET https://chatbotstudio.rezayogaswara.dev/api/v1/template/template-contents/d92c9539-13a0-4aa6-b8dd-2ab1ee88da82/
accept: application/json
Content-Type: application/json
Authorization: Bearer {{access_token}}

###

POST https://chatbotstudio.rezayogaswara.dev/api/v1/template-contents/
accept: application/json
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "parent_ids": [
        {
        "option": "Yes Ok",
        "parent_id": "2d6f9901-e6f5-42b3-be03-7a4986d0bac9",
        "option_label": "Option label Yes",
        "option_position": {"x": 14, "y": 36}
        },
        {
        "option": "No",
        "parent_id": "2d6f9901-e6f5-42b3-be03-7a4986d0bac9",
        "option_label": "Option label No",
        "option_position": {"x": 22, "y": 64}
        }
   ],
  "payloads": [{
    "messaging_product": "whatsapp",
    "recipient_type": "individual",
    "to": "{{Recipient-Phone-Number}}",
    "type": "interactive",
    "interactive": {
        "type": "button",
        "body": {
            "text": "<BUTTON_TEXT>"
        },
        "action": {
            "buttons": [
                {
                    "type": "reply",
                    "reply": {
                        "id": "<b1>",
                        "title": "<BUTTON_TITLE_1>"
                    }
                },
                {
                    "type": "reply",
                    "reply": {
                        "id": "<b2>",
                        "title": "<BUTTON_TITLE_2>"
                    }
                }
            ]
        }
    }
  },{
    "messaging_product": "whatsapp",
    "recipient_type": "individual",
    "to": "{{Recipient-Phone-Number}}",
    "type": "text",
    "text": {
        "preview_url": true,
        "body": "text-message-content #2"
    }
  },{
    "messaging_product": "whatsapp",
    "recipient_type": "individual",
    "to": "{{Recipient-Phone-Number}}",
    "type": "interactive",
    "interactive": {
        "type": "list",
        "header": {
            "type": "text",
            "text": "<HEADER_TEXT>"
        },
        "body": {
            "text": "<BODY_TEXT>"
        },
        "footer": {
            "text": "<FOOTER_TEXT>"
        },
        "action": {
            "button": "<BUTTON_TEXT>",
            "sections": [
                {
                    "title": "<s1>",
                    "rows": [
                        {
                            "id": "<a>",
                            "title": "<SECTION_1_ROW_1_TITLE>",
                            "description": "<SECTION_1_ROW_1_DESC>"
                        },
                        {
                            "id": "<b>",
                            "title": "<SECTION_1_ROW_2_TITLE>",
                            "description": "<SECTION_1_ROW_2_DESC>"
                        }
                    ]
                },
                {
                    "title": "<s2>",
                    "rows": [
                        {
                            "id": "<c>",
                            "title": "<SECTION_2_ROW_1_TITLE>",
                            "description": "<SECTION_2_ROW_1_DESC>"
                        },
                        {
                            "id": "<d>",
                            "title": "<SECTION_2_ROW_2_TITLE>",
                            "description": "<SECTION_2_ROW_2_DESC>"
                        }
                    ]
                }
            ]
        }
    }
  }],
  "label": "init",
  "position": {"x": 13, "y": 22} ,
  "template_id": "dff780ba-1428-4f1d-b185-e475459289fa"
}

###

DELETE https://chatbotstudio.rezayogaswara.dev/api/v1/template-contents/d92c9539-13a0-4aa6-b8dd-2ab1ee88da82/
accept: application/json
Content-Type: application/json
Authorization: Bearer {{access_token}}

###

DELETE https://chatbotstudio.rezayogaswara.dev/api/v1/templates/f99a6751-f44f-4f55-8d63-1dd0175bae9c/
accept: application/json
Content-Type: application/json
Authorization: Bearer {{access_token}}

###

PUT https://chatbotstudio.rezayogaswara.dev/api/v1/templates/f99a6751-f44f-4f55-8d63-1dd0175bae9c/
accept: application/json
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "client": " o p e n m e d i a ",
  "channel_account_alias": " o p e n m e d i a ",
  "template_name": "Template  o p e n m e d i a ",
  "template_description": "Desc Template  o p e n m e d i a ",
  "division_id": " o p e n m e d i a ?"
}

###

GET https://chatbotstudio.rezayogaswara.dev/api/v1/templates/0cccf76d-5741-4cfb-b5c0-4feccc580d12/
accept: application/json
Content-Type: application/json
Authorization: Bearer {{access_token}}

###

GET https://chatbotstudio.rezayogaswara.dev/api/v1/user/templates/
accept: application/json
Content-Type: application/json
Authorization: Bearer {{access_token}}

###

PUT https://chatbotstudio.rezayogaswara.dev/api/v1/template-contents/8f81c734-68ee-4516-a255-669f1db0ccce/
accept: application/json
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "parent_ids": null,
    "payloads": [
      {
        "to": "{{08123456789}}",
        "type": "interactive",
        "interactive": {
          "body": {
            "text": "<BUTTON_TEXT>"
          },
          "type": "button",
          "action": {
            "buttons": [
              {
                "type": "reply",
                "reply": {
                  "id": "<UNIQUE_BUTTON_ID_1>",
                  "title": "<BUTTON_TITLE_1>"
                }
              },
              {
                "type": "reply",
                "reply": {
                  "id": "<UNIQUE_BUTTON_ID_2>",
                  "title": "<BUTTON_TITLE_2>"
                }
              }
            ]
          }
        },
        "recipient_type": "individual",
        "messaging_product": "whatsapp"
      }
    ],
    "position": {
      "x": 10,
      "y": 20
    },
    "created_at": "2022-10-13T05:03:23.370869+00:00",
    "template_id": "f562ec6c-df11-4e7e-a69a-4278ec6c41d4",
    "label": "init 123",
    "is_deleted": true
}

###

GET https://chatbotstudio.rezayogaswara.dev/api/v1/template-contents/a194cdbd-0894-4828-afb3-d5273602b463/
accept: application/json
Content-Type: application/json
Authorization: Bearer {{access_token}}

###

POST https://chatbotstudio.rezayogaswara.dev/api/v1/templates/
accept: application/json
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "client_id": "a b c d e f g h i j k l m n o p q r s t u v w x y z",
  "channel_id": "a b c d e f g h i j k l m n o p q r s t u v w x y z",
  "account_id": "a b c d e f g h i j k l m n o p q r s t u v w x y z",
  "account_alias": "a b c d e f g h i j k l m n o p q r s t u v w x y z",
  "template_name": "Template a b c d e f g h i j k l m n o p q r s t u v w x y z",
  "template_description": "Desc Template a b c d e f g h i j k l m n o p q r s t u v w x y z",
  "division_id": "a b c d e f g h i j k l m n o p q r s t u v w x y z?"
}