###
POST https://chatbotstudio.rezayogaswara.dev/api/v1/token/
accept: application/json
Content-Type: application/json

{
  "username": "reza",
  "password": "reza"
}

> {% client.global.set("access_token", response.body.access_token); %}


####

GET https://chatbotstudio.rezayogaswara.dev/api/v1/users/
accept: application/json
Content-Type: application/json

####
#
#POST https://chatbotstudio.rezayogaswara.dev/api/v1/users/
#accept: application/json
#Content-Type: application/json
#
#{
#  "username": "efcd",
#  "name": "efcd",
#  "password": "efcd",
#  "email": "reza.yoga@live.com",
#  "is_active": false
#}

###

GET https://chatbotstudio.rezayogaswara.dev/api/v1/templates/5ae749fb-a61e-4747-ba9d-f5400a826829/
accept: application/json
Content-Type: application/json
Authorization: Bearer {{access_token}}

###
#
#POST https://chatbotstudio.rezayogaswara.dev/api/v1/template-contents/
#accept: application/json
#Content-Type: application/json
#Authorization: Bearer {{access_token}}
#
#{
#  "parent_id": "-",
#  "payload": {
#    "messaging_product": "whatsapp",
#    "recipient_type": "individual",
#    "to": "{{Recipient-Phone-Number}}",
#    "type": "text",
#    "text": {
#        "preview_url": false,
#        "body": "text-message-content"
#    }
#  },
#  "option": "init",
#  "template_id": "a24bc2a9-9f38-4eb7-858b-94a93d4a2de2"
#}

###

#DELETE https://chatbotstudio.rezayogaswara.dev/api/v1/template-contents/f9d1ca3a-4fd7-4450-8f57-0459a3d323a3/
#accept: application/json
#Content-Type: application/json
#Authorization: Bearer {{access_token}}

###

#DELETE https://chatbotstudio.rezayogaswara.dev/api/v1/templates/2589349e-0877-49ef-9edc-fbe05d0c3d2c/
#accept: application/json
#Content-Type: application/json
#Authorization: Bearer {{access_token}}

###

PUT https://chatbotstudio.rezayogaswara.dev/api/v1/templates/888567fc-2f83-46f2-82b6-7917f9a2c0c3/
accept: application/json
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "client": "iuy",
  "channel_account_alias": "iuy",
  "template_name": "Template iuy",
  "template_description": "Desc Template iuy",
  "division_id": "iuy?"
}

###

GET https://chatbotstudio.rezayogaswara.dev/api/v1/templates/888567fc-2f83-46f2-82b6-7917f9a2c0c3/
accept: application/json
Content-Type: application/json
Authorization: Bearer {{access_token}}

###

#PUT https://chatbotstudio.rezayogaswara.dev/api/v1/template-contents/e233b0a6-ca6a-449f-8045-d008d77d990c/
#accept: application/json
#Content-Type: application/json
#Authorization: Bearer {{access_token}}
#
#{
#  "parent_id": "-",
#  "payload": {
#    "messaging_product": "whatsapp",
#    "recipient_type": "individual",
#    "to": "{{Recipient-Phone-Number}}",
#    "context": {
#        "message_id": "<MSGID_OF_PREV_MSG>"
#    },
#    "type": "location",
#    "location": {
#        "latitude": "<LOCATION_LATITUDE>",
#        "longitude": "<LOCATION_LONGITUDE>",
#        "name": "<LOCATION_NAME>",
#        "address": "<LOCATION_ADDRESS>"
#    }
#},
#  "option": "init",
#  "template_id": "a24bc2a9-9f38-4eb7-858b-94a93d4a2de2"
#}

###

#GET https://chatbotstudio.rezayogaswara.dev/api/v1/template-contents/a24bc2a9-9f38-4eb7-858b-94a93d4a2de2/
#accept: application/json
#Content-Type: application/json
#Authorization: Bearer {{access_token}}

###

#POST https://chatbotstudio.rezayogaswara.dev/api/v1/templates/
#accept: application/json
#Content-Type: application/json
#Authorization: Bearer {{access_token}}
#
#{
#  "client": "wqgv",
#  "channel": "wqgv",
#  "channel_account_alias": "wqgv",
#  "template_name": "Template wqgv",
#  "template_description": "Desc Template wqgv",
#  "division_id": "wqgv?"
#}