###
POST https://chatbotstudio.rezayogaswara.dev/api/v1/token/
accept: application/json
Content-Type: application/x-www-form-urlencoded

grant_type=&username=reza&password=reza&scope=&client_id=&client_secret=


> {% client.global.set("access_token", response.body.access_token); %}

###
#
#POST https://chatbotstudio.rezayogaswara.dev/api/v1/template-contents/
#accept: application/json
#Content-Type: application/json
#Authorization: Bearer {{access_token}}
#
#{
#  "parent_id": "-",
#  "payload": {
#    "messaging_product": "whatsapp",
#    "recipient_type": "individual",
#    "to": "{{Recipient-Phone-Number}}",
#    "type": "text",
#    "text": {
#        "preview_url": false,
#        "body": "text-message-content"
#    }
#  },
#  "option": "init",
#  "template_id": "a24bc2a9-9f38-4eb7-858b-94a93d4a2de2"
#}

###

#DELETE https://chatbotstudio.rezayogaswara.dev/api/v1/template-contents/fab565df-6e2b-4b90-854e-5fd2ac4a1ffd/
#accept: application/json
#Content-Type: application/json
#Authorization: Bearer {{access_token}}

###

PUT https://chatbotstudio.rezayogaswara.dev/api/v1/templates/2589349e-0877-49ef-9edc-fbe05d0c3d2c/
accept: application/json
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "client": "y",
  "channel": "y",
  "channel_account_alias": "y",
  "template_name": "Template y",
  "template_description": "Desc Template y",
  "division_id": "y?"
}

###

#PUT https://chatbotstudio.rezayogaswara.dev/api/v1/template-contents/e81cd1cd-ec3a-4ebf-bba6-0864107ca844/
#accept: application/json
#Content-Type: application/json
#Authorization: Bearer {{access_token}}
#
#{
#  "parent_id": "-",
#  "payload": {
#    "messaging_product": "whatsapp",
#    "recipient_type": "individual",
#    "to": "{{Recipient-Phone-Number}}",
#    "type": "interactive",
#    "interactive": {
#        "type": "list",
#        "header": {
#            "type": "text",
#            "text": "<HEADER_TEXT>"
#        },
#        "body": {
#            "text": "<BODY_TEXT>"
#        },
#        "footer": {
#            "text": "<FOOTER_TEXT>"
#        },
#        "action": {
#            "button": "<BUTTON_TEXT>",
#            "sections": [
#                {
#                    "title": "<s1>",
#                    "rows": [
#                        {
#                            "id": "<a>",
#                            "title": "<SECTION_1_ROW_1_TITLE>",
#                            "description": "<SECTION_1_ROW_1_DESC>"
#                        },
#                        {
#                            "id": "<b>",
#                            "title": "<SECTION_1_ROW_2_TITLE>",
#                            "description": "<SECTION_1_ROW_2_DESC>"
#                        }
#                    ]
#                },
#                {
#                    "title": "<s2>",
#                    "rows": [
#                        {
#                            "id": "<a>",
#                            "title": "<SECTION_2_ROW_1_TITLE>",
#                            "description": "<SECTION_2_ROW_1_DESC>"
#                        },
#                        {
#                            "id": "<b>",
#                            "title": "<SECTION_2_ROW_2_TITLE>",
#                            "description": "<SECTION_2_ROW_2_DESC>"
#                        }
#                    ]
#                }
#            ]
#        }
#    }
#  },
#  "option": "init",
#  "template_id": "a24bc2a9-9f38-4eb7-858b-94a93d4a2de2"
#}

###
#GET https://chatbotstudio.rezayogaswara.dev/api/v1/template-contents/a24bc2a9-9f38-4eb7-858b-94a93d4a2de2/
#accept: application/json
#Content-Type: application/json
#Authorization: Bearer {{access_token}}

###

#POST https://chatbotstudio.rezayogaswara.dev/api/v1/templates/
#accept: application/json
#Content-Type: application/json
#Authorization: Bearer {{access_token}}
#
#{
#  "client": "cbx",
#  "channel": "cbx",
#  "channel_account_alias": "cbx",
#  "template_name": "Template CBx",
#  "template_description": "Desc Template CBx",
#  "division_id": "cbx?"
#}