version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./compose/local/fastapi/Dockerfile
    image: backend_web
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # '/start' is the shell script used to run the service
    command: /start
    # this volume is used to map the files and folders on the host to the container
    # so if we change code on the host, code in the docker container will also be changed
    volumes:
      - .:/app
    ports:
      - 8020:8000
    env_file:
      - .env/.env
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    # this volume is used to map the files and folders on the host to the container
    # so if we change code on the host, code in the docker container will also be changed
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    depends_on:
      - web

  redis:
    image: redis:latest

  celery_worker:
    build:
      context: .
      dockerfile: ./compose/local/fastapi/Dockerfile
    image: backend_celery_worker
    command: /start-celeryworker
    volumes:
      - .:/app
    env_file:
      - .env/.env
    depends_on:
      - redis

  celery_beat:
    build:
      context: .
      dockerfile: ./compose/local/fastapi/Dockerfile
    image: backend_celery_beat
    command: /start-celerybeat
    volumes:
      - .:/app
    env_file:
      - .env/.env
    depends_on:
      - redis

  flower:
    build:
      context: .
      dockerfile: ./compose/local/fastapi/Dockerfile
    image: backend_celery_flower
    command: /start-flower
    volumes:
      - .:/app
    env_file:
      - .env/.env
    ports:
      - 5558:5555
    depends_on:
      - redis
